### ISSUE TITLE
Error: does not appear to be an xcode project (no xcode project file)

### ISSUE THREAD

**Issue by eastskykang** [brant-hwang/cordova-nice-plugin#1]
```
Failed to install 'cordova-nice-plugin':Error: does not appear to be an xcode project (no xcode project file)
    at Object.module.exports.parseProjectFile (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/platforms/ios.js:259:19)
    at PlatformApiPoly.addPlugin (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/platforms/PlatformApiPoly.js:246:71)
    at handleInstall (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:603:6)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:382:28
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:509:49
    at flush (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:108:17)
    at nextTickCallbackWith0Args (node.js:452:9)
Error: does not appear to be an xcode project (no xcode project file)
```

**Comment by eastskykang** [comment]
package 폴더 삭제한 뒤에 plugin add 하고 prepare하면 정상적으로 설치 됨
